### ISSUE TITLE
Earn Section Bug

### ISSUE THREAD

**Issue by rudyblink** [GaloyMoney/blink-mobile#3254]
**Describe the bug**
Users are unable to continue through the earn section because nothing appears on their screen, just the blue background.

**To Reproduce**

1. Go to 'Earn'
2. Select a lesson
3. See the error

**Expected behavior**
The users expect to encounter bitcoin lessons on the Earn section. 

**Screenshots**
![WhatsApp Image 2024-05-08 at 10 05 43 AM](https://github.com/GaloyMoney/blink-mobile/assets/156244225/76d1e9d5-fc67-4899-bddd-16c5a76305d9)
![bug-earn1](https://github.com/GaloyMoney/blink-mobile/assets/156244225/f851f866-f8d6-4352-b35c-3f2ebae7610e)

**Smartphone (please complete the following information):**

- Device: iPhone 13
- OS: iOS 17.4.1
- Version 2.2.263

**Additional context**
Note that this is happening on a lot of different devices

**Comment by Destinysmart** [comment]
Same here... I've been experiencing this same issue too

**Comment by sandipndev** [comment]
I think this has been fixed in the latest beta build. Can you guys update and confirm?

**Comment by Destinysmart** [comment]
https://github.com/GaloyMoney/blink-mobile/assets/169302821/a9721034-efdb-4cbc-8531-3502bf41965f

**I did a short video about the bug...**

The EARN Section is still the same at my end.

**Mobile device (Samsung A12)**

All the way from Nigeria 🇳🇬 

Thanks Guys...
